travis:
  secure:
    BINSTAR_TOKEN: XUhcKTuCFctN4Lxhq7kMcQPKVo046rrJLqU1YXjkwWcT/UzGrZTDlIMK2JleOTmCXlksbFt0M29Akde735lomG3r5ZfwiQIN/8L9F/TncbkZ3zCxs9p/0ZNKzySF+vEDwYC5WlFNEFRfMLcVgyLuuWnxej3Y/TVuQwzxwj2pXH/lVb9c/0+Bar7pTvqh9Bp2HKm9kf+MyJ1TyG/MB9JQa/Xk3Dj+TwjhRkGjTe8FIHmm4yrspaAloADozzvleYl+UYTx9R8WKU3YDH8o1+9kcWKyKbzJdQ6k6k7t0eEAsfjDRWNDge1nqXCYNGCll3/JntwzMeBNU3oEPd1tYPUyhIRgttP5KZmXYXflRHvvqAoRcb6J9wMN55m8Vr7Jj7eWcI5ZvatJ0GobWJNmBmF1LIExV++qbD+fgHc+BaX240HGV2H4EaW4PecmTl1MslV0GrO3xo1a+IuzQ0vvP/X2WhxwdvVFhKIzfipWS3ikCb5Lw4kyoPvmyX/KGQvx7iZ6t/Hmp4XxPZgMaTItrhY6savrvgIK4jf58ZKzXBnEnSukKjC/3nyxiZRNpAEvCzgJ4hotmj1/sAWEjT4fm1ybna+aIrISnu1YoXphSXcX/+TDwg9KORnJtaAuMqhXS9XEtPGG7d2xhTZbw6ajmGvwcqItD8ORdL7HaIGJkBWLO1g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
